export const products = [

  {
    id: 9992,
    img: "/img/merntodo.jpg",
    title: "Mern-Stack Todo Auth-Authzrtn",
    category: "MongoDB / Express / Rest API / React / Redux / Toolkit / JWT /",
    link: "https://reactredux-todoapp-withauth-fe.netlify.app",
    github: "https://github.com/YavuzGurdal/reactredux-todoapp-withauth-fe",
  },
  {
    id: 9993,
    img: "/img/goals.jpg",
    title: "Mern-Stack Auth-Authzrtn-Goals",
    category: "MongoDB / Express / Rest API / React / Redux /",
    link: "https://mernstack-auth-autorztn-goals.herokuapp.com/",
    github: "https://github.com/YavuzGurdal/auth-goals-mernstack",
  },
  {
    id: 9994,
    img: "/img/todolistwithcontextapi.jpg",
    title: "ToDo App with React Context Api",
    category: "React / Context Api / UseRef / css",
    link: "https://todolist-react-contextapi.netlify.app/",
    github: "https://github.com/YavuzGurdal/React_ToDoList_Hooks-ContextApi-Last",
  },
  {
    id: 9995,
    img: "/img/marvelHeroesCards.jpeg",
    title: "Marvel Heroes Cards",
    category: "React / Axios / css",
    link: "https://marvel-heroes-cardss.netlify.app/",
    github: "https://github.com/YavuzGurdal/MarvelHeroesCards",
  }, {
    id: 9996,
    img: "/img/todoListApp.jpg",
    title: "todo list app",
    category: "React / css",
    link: "https://yavuzgurdal.github.io/react_todo_list_app/",
    github: "https://github.com/YavuzGurdal/react_todo_list_app",
  },
  {
    id: 9997,
    img: "/img/currencyApp.jpg",
    title: "currency app",
    category: "JAVASCRIPT / css",
    link: "https://yavuzgurdal.github.io/CurrencyApp/",
    github: "https://github.com/YavuzGurdal/CurrencyApp",
  },
  {
    id: 9998,
    img: "/img/RockPaperScissors.jpg",
    title: "rock-paper-scissors game",
    category: "JAVASCRIPT",
    link: "https://yavuzgurdal.github.io/JS_Rock-Paper-Scissors-Game/",
    github: "https://github.com/YavuzGurdal/JS_Rock-Paper-Scissors-Game",
  },
  {
    id: 9999,
    img: "/img/carRace.jpg",
    title: "car race",
    category: "JAVASCRIPT",
    link: "https://yavuzgurdal.github.io/JS_Car-Race/",
    github: "https://github.com/YavuzGurdal/JS_Car-Race",
  },
  {
    id: 10000,
    img: "/img/number-guessing-game.jpg",
    title: "Number-Guessing-Game",
    category: "JAVASCRIPT",
    link: "https://yavuzgurdal.github.io/JS_Number-Guessing-Game/",
    github: "https://github.com/YavuzGurdal/JS_Number-Guessing-Game",
  },
  {
    id: 2,
    img: "/img/procreator-ux-design-studio-VzJjPuk53sk-unsplash.jpg",
    title: "Portfolio Website",
    link: "https://yavuzgurdal.netlify.app/",
    github: "https://github.com/YavuzGurdal/React_Portfolio_1",
    //github: "https://github.com/YavuzGurdal",
  },
];
