export const products = [
  {
    id: 9996,
    img: "/img/todoListApp.png",
    title: "todo list app",
    category: "React / css",
    link: "https://yavuzgurdal.github.io/react_todo_list_app/",
    github: "https://github.com/YavuzGurdal/react_todo_list_app",
  },
  {
    id: 9997,
    img: "/img/currencyApp.png",
    title: "currency app",
    category: "JAVASCRIPT / css",
    link: "https://yavuzgurdal.github.io/CurrencyApp/",
    github: "https://github.com/YavuzGurdal/CurrencyApp",
  },
  {
    id: 9998,
    img: "/img/tas-kagit-makas2.jpeg",
    title: "rock-paper-scissors game",
    category: "JAVASCRIPT",
    link: "https://yavuzgurdal.github.io/JS_Rock-Paper-Scissors-Game/",
    github: "https://github.com/YavuzGurdal/JS_Rock-Paper-Scissors-Game",
  },
  {
    id: 9999,
    img: "/img/carRace.png",
    title: "car race",
    category: "JAVASCRIPT",
    link: "https://yavuzgurdal.github.io/JS_Car-Race/",
    github: "https://github.com/YavuzGurdal/JS_Car-Race",
  },
  {
    id: 10000,
    img: "/img/NumberGuessinGame.png",
    title: "Number-Guessing-Game",
    category: "JAVASCRIPT",
    link: "https://yavuzgurdal.github.io/JS_Number-Guessing-Game/",
    github: "https://github.com/YavuzGurdal/JS_Number-Guessing-Game",
  },
  {
    id: 2,
    img: "/img/procreator-ux-design-studio-VzJjPuk53sk-unsplash.jpg",
    link: "https://yavuzgurdal.netlify.app/",
    github: "https://github.com/YavuzGurdal",
  },
];
